# Generated by Django 5.0.3 on 2024-03-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=100)),
                ('plan_estudios', models.CharField(max_length=100)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Carreras',
                'db_table': 'carreras',
            },
        ),
    ]
